version: "3.8"
services:
  sdk:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    volumes:                                                                                         
      - ./config:/root/.config
      - ./kube:/root/.kube
